services: 
  # Sources Image - Use this image to easily pull in various source projects!
  latest:
    image: ${IMAGE_NAME:?err}:${IMAGE_VERSION:-latest}
    command: /sbin/init
    build:
      context: .
      args:
        VERSION: sources
        IMAGE_NAME: ${IMAGE_NAME:?err}
        IMAGE_VERSION: ${IMAGE_VERSION:-latest}
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME:?err}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION:?err}
        HOMEDIR: ${HOMEDIR:?err}
        MAINTAINER: ${MAINTAINER:?err}
        THEEMAIL: ${THEEMAIL:?err}
  # Bootable version of this image
  #latest-bootable:
  #  image: ${IMAGE_NAME:?err}:${IMAGE_VERSION:-latest-bootable}
  #  command: /sbin/init
  #  build:
  #    context: .
  #    args:
  #      VERSION: sources-bootable
  #      IMAGE_NAME: ${IMAGE_NAME:?err}
  #      IMAGE_VERSION: ${IMAGE_VERSION:-latest-bootable}
  #      BASE_IMAGE_NAME: ${BASE_IMAGE_NAME:?err}
  #      BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION:?err}
  #      HOMEDIR: ${HOMEDIR:?err}
  #      MAINTAINER: ${MAINTAINER:?err}
  #      THEEMAIL: ${THEEMAIL:?err}
