name: Release Drafter

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  release-drafter:
    name: Draft Release
    uses: deepworks-net/github.toolkit/.github/workflows/release-drafter.yml@v1
    with:
      draft: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}